CREATE TABLE usuarios (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100),
email VARCHAR(100),
password VARCHAR(255),
rol VARCHAR(20)
);


CREATE TABLE productos (
id INT AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(100),
precio DECIMAL(10,2),
stock INT
);


CREATE TABLE pedidos (
id INT AUTO_INCREMENT PRIMARY KEY,
id_usuario INT,
total DECIMAL(10,2),
fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);